### PR TITLE
some clean and port to 9.4

### PR DESCRIPTION
**Pull request by orthagh**
For information, the current codebase is still compatible with 9.3 (not 9.2) so i didn't restrict the old version in setup.

Here is the big list:
- added constants for manipulating GLPI versions in top of setup file
- remove manual checks of GLPI version as core now checks it itself since 9.3.
- removed a lot of unused vars and globals (hint use [phpmd](https://phpmd.org/) :) )
- `getType` method is static
- Don't use `getID` method for data manipulation, this method aims to display text (and can return "N/A")
- lot of code style matching GLPI CS (there's more to do)
- `DbUtils` exists for unit tests, we don't plan to drop old functions (not today)
- used `dropdownAllItems` ajax file for secondary dropdown (for more loosing checks), you are using helpdesk itemtype restriction, is it wanted ? On my side i would have used `$CFG_GLPI["asset_types"]` or maybe `$CFG_GLPI["ticket_types"]` (more stuff in that list). This choice leads to double configuration, one for profile, another one in plugin setup. What do you think ?

One last point, there is a lot of commented code, could we could clean all this stuff ?

### CODE REVIEW

**Comment by orthagh** [comment]
ping @tomolimo

**Comment by tomolimo** [comment]
Thank you @orthagh 
I'll check that asap :+1: 

>  you are using helpdesk itemtype restriction, is it wanted ?

not really, I'll change that part to be able to use any Object type (also from plugins).

**Comment by orthagh** [comment]
Ok, i will push a change for itemtype list so

**Comment by orthagh** [comment]
Added icon + screenshots for plugins directory.
@tomolimo do you have some time for review and merge ?

**Comment by orthagh** [comment]
Also #3 should be fixed by this part: https://github.com/tomolimo/impacts/pull/2/files#diff-15cea08f657239af5265c8ad277bdd65R143

**Comment by peteredhair** [comment]
Port for 9.4,...., great, and thanks to all

**Comment by orthagh** [comment]
For information, we started an implementation in glpi core (target next major version 9.5).
Check https://github.com/glpi-project/glpi/pull/5954

it will comes with:

- a better library
- png export
- virtual (and named) groups
- edges manipulation
- saving of node/edge positions
- full ui (toolbar) to manipulate your schema
- better default layout

Footage of a pre-alpha (broken as hell) version
image


Btw, thanks to @tomolimo for the kickstart of the feature.

**Comment by tomolimo** [comment]
Hello @orthagh 
Thank you for the information.
Got a question: will the current DB tables (config and impacts) be migrated during the migration process?
Thank you
Regards,
Tomolimo

**Comment by orthagh** [comment]
i don't know yet.
We currently concentrate our efforts on adding features and we not ready at all.

The swap of the library was pretty consuming.

So i can't answer, yet, but i think it will be pretty easy

**Pull request merged**
