### PR TITLE
Added support for GLPI 9.5

### PR DESCRIPTION
**Pull request by pbfoliveira**
Hi @tomolimo,

Added support for GLPI 9.5. Already tested here at my job and all working fine with previous data.

image
image

### CODE REVIEW

**Comment by tomolimo** [comment]
Hello @pbozzi 

Thank you for this PR, but did you see that in GLPI 9.5, an impact feature has been implemented into GLPI core?

Regards,
Tomolimo

**Comment by pbfoliveira** [comment]
Hi @tomolimo ,

There is such feature indeed, but it does not fit my needs. Actually I use _webapplications_ plugin and it isn't compatible with new impacts feature yet.

**Comment by tomolimo** [comment]
Hello @pbozzi 

I'm going to provide a new release for the impacts plugin, and it will bring:

1. a migration of the impacts plugin data into the core tables
2. a possibility to add/Edit/Delete other asset types than the one proposed in the core.

This will provide a complete migration path, doing the migration with used asset types (even if they are provided by plugins).

This new version is under development phase, I hope that before end of the week it will be released.

Thank you,
Regards,
Tomolimo

**Comment by pbfoliveira** [comment]
Great @tomolimo !

**Comment by tomolimo** [comment]
Fixed by https://github.com/tomolimo/impacts/releases/tag/2.0.3

**Pull request closed without merging**
